Fix Overlapped Semester Checker
maqnitude/uit-planner pull request #54
Opened 2024-01-21 18:41 UTC by Jun0se7en

2024-01-23 02:47 UTC, maqnitude requested changes
Sync repo, resolve the conflicts, and link to the appropriate issue(s).

2024-01-23 02:47 UTC, maqnitude commented on src/components/SearchBars.tsx
Change the tab size to 2.

2024-01-25 08:32 UTC, LukasAbraham approved these changes
Your PR still needs to be refactored

2024-01-25 08:32 UTC, LukasAbraham commented on src/screens/EditSemesterScreen.tsx
> +            (newSemesterStartTime <= existingSemesterStartTime && newSemesterEndTime >= existingSemesterEndTime)) {
You didn't fix your if statements

2024-01-25 08:32 UTC, LukasAbraham commented on src/screens/CoursesScreen.tsx
> +
We don't need another useEffect hook here.

2024-01-25 08:35 UTC, maqnitude approved these changes

2024-01-25 08:36 UTC, merged